### ISSUE TITLE
Each week should have a main file

### ISSUE THREAD

**Issue by axecopfire** [Vets-Who-Code/web-curriculum#23]
# Overview

Each week should have a main file. That way we could standardize links from other places. For example, we could standardize links from the base README to each week's `README` i.e. `[## Week 2 - HTML && CSS](week-01/README.md)`

Currently each week's files are broken up by day. I think it's unrealistic to have the curriculum broken up that granularly.

I propose each week have a `README.md`

**Comment by myquite** [comment]
I'll take this one.
