### ISSUE TITLE
Divops/Serverless connection

### ISSUE THREAD

**Issue by axecopfire** [Vets-Who-Code/web-curriculum#30]
Blocks 1/2 focus mainly on Frontend and building UIs. However, when we hit block 3 we introduce Docker. You can't really dockerize UIs because they're ran in browsers. So what really needs dockerization when it comes to frontend?

* An idea is that we start the course off by having students download and run their dev envs from a Docker container (so as not to even have node on their computers).

**Comment by jeromehardaway** [comment]
Hmmm,
I will look more into this. WOuld require them installing docker as a part of installfest.
